import type { Problem, TestCase } from "./problems";
import { formatType, primArrayElement, type KType, type NodeName, type ScalarName } from "./types";

export type HarnessMode = "run" | "check";

const IO = "WinnieIO";

const SCALAR_DECODERS: Record<ScalarName, string> = {
  Int: "int",
  Long: "long",
  Double: "double",
  Boolean: "bool",
  Char: "char",
  String: "str",
};

const SCALAR_ENCODERS: Record<ScalarName, string> = {
  Int: "encInt",
  Long: "encLong",
  Double: "encDouble",
  Boolean: "encBool",
  Char: "encChar",
  String: "encStr",
};

const NODE_DECODERS: Record<NodeName, string> = {
  ListNode: "listNode",
  TreeNode: "treeNode",
  DoublyListNode: "doublyListNode",
};

const NODE_ENCODERS: Record<NodeName, string> = {
  ListNode: "encListNode",
  TreeNode: "encTreeNode",
  DoublyListNode: "encDoublyListNode",
};

/** Kotlin expression converting the WinnieLit expression `lit` into a value of type `t`. */
export function decodeExpr(t: KType, lit: string, depth = 1): string {
  const x = `x${depth}`;
  switch (t.kind) {
    case "scalar":
      return `${IO}.${SCALAR_DECODERS[t.name]}(${lit})`;
    case "node":
      return `${IO}.${NODE_DECODERS[t.name]}(${lit})`;
    case "primArray": {
      const element: KType = { kind: "scalar", name: primArrayElement(t.name) };
      return `${IO}.items(${lit}).map { ${x} -> ${decodeExpr(element, x, depth + 1)} }.to${t.name}()`;
    }
    case "array":
      return `${IO}.items(${lit}).map { ${x} -> ${decodeExpr(t.of, x, depth + 1)} }.toTypedArray()`;
    case "list":
      return `${IO}.items(${lit}).map { ${x} -> ${decodeExpr(t.of, x, depth + 1)} }`;
  }
}

/** Kotlin expression converting `value` (of type `t`) into canonical LeetCode literal text. */
export function encodeExpr(t: KType, value: string, depth = 1): string {
  const y = `y${depth}`;
  switch (t.kind) {
    case "scalar":
      return `${IO}.${SCALAR_ENCODERS[t.name]}(${value})`;
    case "node":
      return `${IO}.${NODE_ENCODERS[t.name]}(${value})`;
    case "primArray": {
      const element: KType = { kind: "scalar", name: primArrayElement(t.name) };
      return `${IO}.encSeq(${value}.map { ${y} -> ${encodeExpr(element, y, depth + 1)} })`;
    }
    case "array":
    case "list":
      return `${IO}.encSeq(${value}.map { ${y} -> ${encodeExpr(t.of, y, depth + 1)} })`;
  }
}

/** Generates Main.kt. In "check" mode it only parses the literals (used by check-problems). */
export function generateMain(problem: Problem, mode: HarnessMode): string {
  const { method } = problem;
  const returns = method.returns;
  const decodeParams = method.params.map(
    (p, i) => `            val p${i}: ${formatType(p.type)} = ${decodeExpr(p.type, `${IO}.parse(input[${i}])`)}`,
  );
  const args = method.params.map((_, i) => `p${i}`).join(", ");
  const body =
    mode === "run"
      ? [
          ...decodeParams,
          `            val result: ${formatType(returns)} = Solution().${method.name}(${args})`,
          `            ${encodeExpr(returns, "result")}`,
        ]
      : [...decodeParams, `            ""`];

  return [
    "// Generated by Winnie Code. Do not edit.",
    "",
    "fun main(args: Array<String>) {",
    "    WinnieRunner.run(",
    "        args,",
    `        normalizeExpected = { expected -> ${encodeExpr(returns, decodeExpr(returns, `${IO}.parse(expected)`))} },`,
    "        invoke = { input ->",
    ...body,
    "        },",
    "    )",
    "}",
    "",
  ].join("\n");
}

const b64 = (s: string) => Buffer.from(s, "utf8").toString("base64");

/** Contents of cases.txt: one line per test with base64 inputs followed by the base64 expected value. */
export function encodeCases(tests: TestCase[]): string {
  return tests.map((t) => [...t.input, t.expected].map(b64).join(" ")).join("\n") + "\n";
}
